### PR TITLE
Upgrade to null-safety support.

### PR DESCRIPTION
**Pull request by creky**

### CODE REVIEW

**Comment by aviyadeveloper** [comment]
Can we get this in? The package is somewhat useless without it.

**Review by algokun — APPROVED** [review]

**Review by mt-tadayon — APPROVED** [review]

**Comment by eliasjtg** [comment]
Any update?

**Review by msjahun — APPROVED** [review]

**Comment by mshenawy22** [comment]
@rodydavis any plans for a new version that supports null safety?

**Comment by vikivyas** [comment]
Upgrading to this version will be good idea...

**Pull request merged**
